# Generated by Django 3.0 on 2020-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_data',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
