# Generated by Django 3.0 on 2020-11-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201129_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_data',
            old_name='certi_id',
            new_name='certi_no',
        ),
    ]
