# Generated by Django 3.0 on 2020-11-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201130_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_data',
            name='certi_no',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
