# Generated by Django 3.0 on 2020-11-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20201130_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_data',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
